/* eslint-disable */
/* global WebImporter */

/**
 * Parser for cards-steps. Base: cards (custom; numbered options).
 * Source: https://www.toyotafinancial.com/us/en/end_of_lease_options/your_option.html
 * Selector (page-templates.json): main > .container-fluid.px-0 .lease-end-right-container > .card-button.parbase
 * Generated: 2026-10-04
 *
 * Content model (blocks/cards-steps/README.md + cards-steps.js decorator — the custom block
 * contract overrides the generic 2-cell Cards convention because steps have no image):
 *   N rows, 1 cell: [h3 title (sup kept), p text..., p > strong > a CTA, p disclaimer (optional, after CTA)]
 *   The step numbers (.option-number) are generated by the block (CSS counter) and are dropped.
 *
 * Source structure (verified in cached source.html):
 *   .card-button.parbase > h2.h2 (empty, dropped) + div
 *     > .your-options-card (x3)
 *       > .option-number > span (number, dropped)
 *       > div.col-md-10 > h4.h4 title, p (some empty), p > i note,
 *           div.w-100 > a.primary-btn.button-link (CTA), p.disclaimer-text (optional)
 */
function cleanText(el) {
  return (el.textContent || '').replace(/ /g, ' ').replace(/\s+/g, ' ').trim();
}

function buildCta(a, document) {
  const link = document.createElement('a');
  link.setAttribute('href', a.getAttribute('href') || '');
  link.textContent = cleanText(a);
  const strong = document.createElement('strong');
  strong.append(link);
  const p = document.createElement('p');
  p.append(strong);
  return p;
}

export default function parse(element, { document }) {
  let cards = [...element.querySelectorAll('.your-options-card')];
  if (!cards.length) {
    // Fallback: any wrapper that holds a step number.
    cards = [...element.querySelectorAll('.option-number')].map((n) => n.parentElement);
  }

  const cells = [];
  cards.forEach((card) => {
    const content = card.querySelector(':scope > div:not(.option-number)') || card;
    const titleEl = content.querySelector('h4, h3, h2, h5');
    const contentCell = [];
    const ctas = [];
    const disclaimers = [];

    if (titleEl && cleanText(titleEl)) {
      const h3 = document.createElement('h3');
      [...titleEl.childNodes].forEach((n) => h3.append(n.cloneNode(true)));
      contentCell.push(h3);
    }

    [...content.children].forEach((child) => {
      if (child === titleEl || child.classList.contains('option-number')) return;
      // CTA wrapper: div.w-100 > a.primary-btn.button-link
      const btn = child.matches('a.primary-btn, a.button-link')
        ? child
        : child.querySelector('a.primary-btn, a.button-link');
      if (btn && child.tagName !== 'P') {
        ctas.push(buildCta(btn, document));
        return;
      }
      if (!cleanText(child) && !child.querySelector('img')) return; // empty <p>
      if (child.classList.contains('disclaimer-text')) {
        disclaimers.push(child);
        return;
      }
      contentCell.push(child);
    });

    if (!contentCell.length && !ctas.length) return;
    // Disclaimer always follows the CTA.
    cells.push([[...contentCell, ...ctas, ...disclaimers]]);
  });

  // Empty-block guard.
  if (!cells.length) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const block = WebImporter.Blocks.createBlock(document, { name: 'cards-steps', cells });
  element.replaceWith(block);
}
